{% set name = "django-db-logger" %}
{% set version = "0.1.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django-db-logger-{{ version }}.tar.gz
  sha256: a299a08638a741eb0b1d192f2a27eae57ed5118673c2aa916467f2e060c24e72

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - django >=1.9
    - six

test:
  imports:
    - django_db_logger
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/CiCiUi/django-db-logger
  summary: Django logging in database
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
